# Generated by Django 3.1 on 2020-09-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.Child'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
