# Generated by Django 3.1 on 2020-09-26 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200926_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability_event',
            name='date',
        ),
        migrations.AddField(
            model_name='availability_event',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability_event',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
