# Generated by Django 3.1 on 2020-09-30 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200930_0059'),
        ('main_app', '0009_auto_20200929_1129'),
    ]

    operations = [
    ]